[build-system]
requires = ["setuptools>=42", "wheel"]

[tool.black]
line-length = 120
target-version =  ['py38', 'py39', 'py310', 'py311', 'py312']
include = '''
^/(
    [^/]*.py
    | (benchmarks|build_scripts|chia|tests|tools)/.*\.pyi?
)$
'''
exclude = ''
